# Header
menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/changyuheng
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: false
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-44162683-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
