# Header
menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/changyuheng
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- recent_posts
- tag

# Miscellaneous
google_analytics: UA-44162683-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
